WORLD_WIDTH = 10
WORLD_HEIGHT = 5
WORLD_DEPTH = 10
GROUND = 0

BLOCK_DECREASE = 1
SUN_VALUE = 2

GENOME_SIZE = 10
GENOME_MUTATION_RATE = 0.01
GENOME_SEED = 42
SEEDCELL_GENE_NUMBER = 1

CELL_ENERGY_CONSUMPTION = 1
ENERGY_CONSUMPTION_INCREASE_RATE = 0.1
INITIAL_ENERGY = 100
GROWTH_COST = 1

INITIAL_POPULATION_SIZE = 2
EXPERIMENT_DURATION = 50
